---
version: 1
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-vvv"
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-29-rhel8:1.0.0-88'
ansible_config: 'ansible.cfg'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - ADD _build/awscliv2.venv.tar.gz /root
    - ENV PATH "/root/awscliv2/bin:${PATH}"
    - RUN echo "export PATH=/root/awscliv2/bin:${PATH}" >> /etc/bashrc
...

